/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 * @author GSM
 * @since 03/04/2018 - 19:11
 * @version 1.5 Los Angeles
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmDirecao = new javax.swing.JMenu();
        jmiCadProfessor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiCriarTurma = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiCadAluno = new javax.swing.JMenuItem();
        jmProfessor = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jmAluno = new javax.swing.JMenu();
        jmiNotas = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GSM Escola");

        jmDirecao.setText("Direção");

        jmiCadProfessor.setText("Cadastrar Professor");
        jmiCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProfessorActionPerformed(evt);
            }
        });
        jmDirecao.add(jmiCadProfessor);
        jmDirecao.add(jSeparator2);

        jmiCriarTurma.setText("Criar Turma");
        jmiCriarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCriarTurmaActionPerformed(evt);
            }
        });
        jmDirecao.add(jmiCriarTurma);
        jmDirecao.add(jSeparator3);

        jmiCadAluno.setText("Cadastrar Aluno");
        jmiCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadAlunoActionPerformed(evt);
            }
        });
        jmDirecao.add(jmiCadAluno);

        jmbMenuPrincipal.add(jmDirecao);

        jmProfessor.setText("Professor");

        jmiDados.setText("Ver/Modificar Dados");
        jmiDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiDadosMouseClicked(evt);
            }
        });
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jmProfessor.add(jmiDados);

        jmbMenuPrincipal.add(jmProfessor);

        jmAluno.setText("Aluno");

        jmiNotas.setText("Ver Notas");
        jmiNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNotasActionPerformed(evt);
            }
        });
        jmAluno.add(jmiNotas);

        jmbMenuPrincipal.add(jmAluno);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmbMenuPrincipal.add(jmSair);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirNotas() {
        UINotas gn = new UINotas();
        jAreaTrabalho.add(gn);
        gn.setVisible(true);
    }

    private void abrirNotasAlunos() {
        UINotasAluno gna = new UINotasAluno();
        jAreaTrabalho.add(gna);
        gna.setVisible(true);
    }

    private void abrirCadAluno() {
        UICadAluno uca = new UICadAluno();
        jAreaTrabalho.add(uca);
        uca.setVisible(true);
    }

    private void abrirCadProfessor() {
        UICadProfessor ucp = new UICadProfessor();
        jAreaTrabalho.add(ucp);
        ucp.setVisible(true);
    }

    private void abrirCriarTurma() {
        UICadTurma uct = new UICadTurma();
        jAreaTrabalho.add(uct);
        uct.setVisible(true);
    }


    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        abrirNotas();
    }//GEN-LAST:event_jmiDadosActionPerformed

    private void jmiDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiDadosMouseClicked
        abrirNotas();
    }//GEN-LAST:event_jmiDadosMouseClicked

    private void jmiNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNotasActionPerformed
        abrirNotasAlunos();
    }//GEN-LAST:event_jmiNotasActionPerformed

    private void jmiCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadAlunoActionPerformed
        abrirCadAluno();
    }//GEN-LAST:event_jmiCadAlunoActionPerformed

    private void jmiCriarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCriarTurmaActionPerformed
        abrirCriarTurma();
    }//GEN-LAST:event_jmiCriarTurmaActionPerformed

    private void jmiCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProfessorActionPerformed
        abrirCadProfessor();
    }//GEN-LAST:event_jmiCadProfessorActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jmAluno;
    private javax.swing.JMenu jmDirecao;
    private javax.swing.JMenu jmProfessor;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiCadAluno;
    private javax.swing.JMenuItem jmiCadProfessor;
    private javax.swing.JMenuItem jmiCriarTurma;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JMenuItem jmiNotas;
    // End of variables declaration//GEN-END:variables
}
