/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ProfessorVO;
import modelo.TurmaVO;
import modelo.Validacao;
import servicos.EscolaServicos;
import servicos.ServicosFactory;

/**
 * @author GSM
 * @since 03/04/2018 - 19:11
 * @version 1.5 Los Angeles
 */
public class UICadTurma extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadTurma
     */
    public UICadTurma() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jbCriarTurma = new javax.swing.JButton();
        jtMateria = new javax.swing.JTextField();
        jlMateriaErro = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criar Turma");

        jLabel1.setText("Matéria");

        jLabel2.setText("Professor");

        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        jbCriarTurma.setText("Criar Turma");
        jbCriarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarTurmaActionPerformed(evt);
            }
        });
        jbCriarTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCriarTurmaKeyPressed(evt);
            }
        });

        jtMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMateriaFocusLost(evt);
            }
        });
        jtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMateriaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 100, Short.MAX_VALUE)
                            .addComponent(jtMateria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlMateriaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jbCriarTurma)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMateriaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jbCriarTurma)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherCombo() {
        try {
            EscolaServicos es = ServicosFactory.getEscolaServicos();
            ArrayList<ProfessorVO> professores = new ArrayList<>();
            professores = es.buscarProfessor();
            jComboBox2.addItem("Selecione uma turma:");
            for (int i = 0; i < professores.size(); i++) {
                jComboBox2.addItem(professores.get(i));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }
    }

    private void cadastrarTurma() {

        try {
            TurmaVO tVO = new TurmaVO();
            if (Validacao.testarNome(jtMateria.getText())) {
                tVO.setMateria(jtMateria.getText());
                tVO.setProfessor((ProfessorVO) jComboBox2.getSelectedItem());
            } else {
                throw new Exception("Texto inválido!");
            }

            EscolaServicos es = ServicosFactory.getEscolaServicos();
            es.cadastrarTurma(tVO);

            JOptionPane.showMessageDialog(this,
                    "Turma cadastrada com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRO! " + e.getMessage());
        }
    }

    private void jbCriarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarTurmaActionPerformed
        cadastrarTurma();
    }//GEN-LAST:event_jbCriarTurmaActionPerformed

    private void limpar(){
        jtMateria.setText("");
        jtMateria.setBackground(Color.WHITE);
        jlMateriaErro.setVisible(false);
    }
    
    private void jtMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMateriaFocusLost
        // TODO add your handling code here:
        if (jtMateria.getText().isEmpty()) {
            jtMateria.setBackground(Color.RED);
            jlMateriaErro.setVisible(true);
            jlMateriaErro.setIcon(
                    new ImageIcon(getClass().getResource("/icones/erro.png")));
        } else {
            jtMateria.setBackground(Color.green);
            jtMateria.setVisible(true);
            jlMateriaErro.setIcon(
                    new ImageIcon(getClass().getResource("/icones/ok.png")));
        }
    }//GEN-LAST:event_jtMateriaFocusLost

    private void jtMateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMateriaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBox2.grabFocus();
        }
    }//GEN-LAST:event_jtMateriaKeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCriarTurma.grabFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jbCriarTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCriarTurmaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarTurma();
            limpar();
        }
    }//GEN-LAST:event_jbCriarTurmaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbCriarTurma;
    private javax.swing.JLabel jlMateriaErro;
    private javax.swing.JTextField jtMateria;
    // End of variables declaration//GEN-END:variables
}
